name: swiss-urbanization
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - pip:
    - -e .
    - python-dotenv>=0.5.1
    - python-slugify==2.0.1
    - pylandstats==0.1.1  
    - awscli
  - setuptools
  - wheel
  - flake8
  - sphinx
  - click
  - coverage
  - python=3
  - boto3=1.9.86
  - tqdm=4.30.0
  - geopandas=0.4.0  
  - numpy=1.15.4  
  - rasterio=1.0.15
  - scipy=1.2.0
