name: swiss-urbanization
channels:
  - conda-forge
dependencies:
  - python=3.7
  - ipykernel
  - nbconvert
  - osmnx
  - pip
  - pylandstats>=2.0.0
  - pyproj>=2.2.0
  - python-dotenv
  - python-slugify
  - seaborn
  - pip:
    - -e .
    - pwlf
    - swisslandstats-geopy>=0.7.3
